name: cd

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  push-to-docker-registry:
    name: push to docker registry
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Run CD"
        run: ./build.cmd PushDockerImage CreateGitHubRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
